version: '3.8'

services:
  web:
    build: .
    command: /app/docker-entrypoint.sh
    volumes:
      - ./SingleCourseWebApp/:/app/
      - static_volume:/app/staticfiles/
      - media_volume:/app/data/media/
    ports:
      - "8008:8008"
