# Generated by Django 5.1.3 on 2024-11-29 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'is_student': True}, related_name='course_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
