# Generated by Django 5.1.3 on 2024-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='Course end date', null=True),
        ),
    ]
